title: Jeff Kaiser
description: Musician, technologist, and scholar, Jeff Kaiser is an active performer, researcher, and creator of experimental music that uses interactive technologies. He is a prolific Max and Max for Live developer, an avid fan of Reaper, and a professor of music technology and composition at the University of Central Missouri..
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
